import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateAllTables1760113079204 implements MigrationInterface {
    name = 'CreateAllTables1760113079204'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."sessions_status_enum" AS ENUM('ACTIVE', 'EXPIRED', 'REVOKED')`);
        await queryRunner.query(`CREATE TABLE "sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "deviceId" uuid, "token" character varying(255) NOT NULL, "status" "public"."sessions_status_enum" NOT NULL DEFAULT 'ACTIVE', "expiresAt" TIMESTAMP NOT NULL, "ipAddress" inet, "userAgent" character varying(255), "location" character varying(100), "lastActiveAt" TIMESTAMP, "revokedAt" TIMESTAMP, "revokedReason" character varying(500), "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_e9f62f5dcb8a54b84234c9e7a06" UNIQUE ("token"), CONSTRAINT "PK_3238ef96f18b355b671619111bc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_50762206f116cd47d1c3fec396" ON "sessions" ("expiresAt") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e9f62f5dcb8a54b84234c9e7a0" ON "sessions" ("token") `);
        await queryRunner.query(`CREATE INDEX "IDX_fd11aa87698d5a784713b9de97" ON "sessions" ("deviceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_57de40bc620f456c7311aa3a1e" ON "sessions" ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."devices_type_enum" AS ENUM('DESKTOP', 'MOBILE', 'TABLET', 'OTHER')`);
        await queryRunner.query(`CREATE TYPE "public"."devices_status_enum" AS ENUM('TRUSTED', 'UNTRUSTED', 'BLOCKED')`);
        await queryRunner.query(`CREATE TABLE "devices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "fingerprint" character varying(255) NOT NULL, "name" character varying(100), "type" "public"."devices_type_enum" NOT NULL DEFAULT 'OTHER', "status" "public"."devices_status_enum" NOT NULL DEFAULT 'UNTRUSTED', "userAgent" character varying(255), "browser" character varying(100), "browserVersion" character varying(50), "os" character varying(100), "osVersion" character varying(50), "lastSeenIp" inet, "location" character varying(100), "lastSeenAt" TIMESTAMP, "trustedAt" TIMESTAMP, "blockedAt" TIMESTAMP, "blockedReason" character varying(500), "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_854ce23dfa9a30aa4ddfc6f78f5" UNIQUE ("fingerprint"), CONSTRAINT "PK_b1514758245c12daf43486dd1f0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_854ce23dfa9a30aa4ddfc6f78f" ON "devices" ("fingerprint") `);
        await queryRunner.query(`CREATE INDEX "IDX_e8a5d59f0ac3040395f159507c" ON "devices" ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."refresh_tokens_status_enum" AS ENUM('ACTIVE', 'USED', 'REVOKED', 'EXPIRED')`);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "token" character varying(255) NOT NULL, "status" "public"."refresh_tokens_status_enum" NOT NULL DEFAULT 'ACTIVE', "expiresAt" TIMESTAMP NOT NULL, "ipAddress" inet, "userAgent" character varying(255), "usedAt" TIMESTAMP, "revokedAt" TIMESTAMP, "revokedReason" character varying(500), "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_4542dd2f38a61354a040ba9fd57" UNIQUE ("token"), CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_56b91d98f71e3d1b649ed6e9f3" ON "refresh_tokens" ("expiresAt") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_4542dd2f38a61354a040ba9fd5" ON "refresh_tokens" ("token") `);
        await queryRunner.query(`CREATE INDEX "IDX_610102b60fea1455310ccd299d" ON "refresh_tokens" ("userId") `);
        await queryRunner.query(`CREATE TABLE "sports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "slug" character varying(100) NOT NULL, "description" character varying(500), "icon" character varying(255), "image" character varying(255), "apiId" character varying(50) NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "sortOrder" integer NOT NULL DEFAULT '0', "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_be96c1d313b6d198a17b08f4c63" UNIQUE ("slug"), CONSTRAINT "UQ_7469a21a84308f52d4b9d14cdd9" UNIQUE ("apiId"), CONSTRAINT "PK_4fa1063d368e1fd68ea63c7d860" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_7469a21a84308f52d4b9d14cdd" ON "sports" ("apiId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_be96c1d313b6d198a17b08f4c6" ON "sports" ("slug") `);
        await queryRunner.query(`CREATE TABLE "seasons" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "leagueId" uuid NOT NULL, "year" integer NOT NULL, "name" character varying(100) NOT NULL, "startDate" date NOT NULL, "endDate" date NOT NULL, "isCurrent" boolean NOT NULL DEFAULT false, "isFinished" boolean NOT NULL DEFAULT false, "standings" jsonb, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_cb8ed53b5fe109dcd4a4449ec9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b6c0d664ab8e5ad1c0df11641f" ON "seasons" ("leagueId", "year") `);
        await queryRunner.query(`CREATE INDEX "IDX_e20814074bbf37638cb4affa08" ON "seasons" ("year") `);
        await queryRunner.query(`CREATE INDEX "IDX_a7cb1734e4ef424bf9422b1c0d" ON "seasons" ("leagueId") `);
        await queryRunner.query(`CREATE TABLE "teams" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "leagueId" uuid NOT NULL, "name" character varying(150) NOT NULL, "slug" character varying(150) NOT NULL, "shortName" character varying(150), "code" character varying(10), "country" character varying(100) NOT NULL, "countryCode" character varying(10), "logo" character varying(255), "venue" character varying(255), "venueAddress" character varying(255), "venueCapacity" integer, "venueImage" character varying(255), "apiId" character varying(50) NOT NULL, "venueId" integer, "isActive" boolean NOT NULL DEFAULT true, "founded" integer, "isNational" boolean NOT NULL DEFAULT false, "colors" jsonb, "form" jsonb, "statistics" jsonb, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_de8536da4945fe980f4a61900d3" UNIQUE ("slug"), CONSTRAINT "UQ_1000526725818dc4f1fa10c05c9" UNIQUE ("apiId"), CONSTRAINT "PK_7e5523774a38b08a6236d322403" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_960b513ff2e8bc3228b7d90884" ON "teams" ("country") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1000526725818dc4f1fa10c05c" ON "teams" ("apiId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_de8536da4945fe980f4a61900d" ON "teams" ("slug") `);
        await queryRunner.query(`CREATE INDEX "IDX_a2e8bdf2708d44fab55ee1ff75" ON "teams" ("leagueId") `);
        await queryRunner.query(`CREATE TYPE "public"."leagues_type_enum" AS ENUM('LEAGUE', 'CUP', 'PLAYOFFS', 'FRIENDLY', 'QUALIFICATION')`);
        await queryRunner.query(`CREATE TABLE "leagues" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sportId" uuid NOT NULL, "name" character varying(150) NOT NULL, "slug" character varying(150) NOT NULL, "description" character varying(500), "type" "public"."leagues_type_enum" NOT NULL DEFAULT 'LEAGUE', "country" character varying(100) NOT NULL, "countryCode" character varying(10), "logo" character varying(255), "flag" character varying(255), "countryFlag" character varying(255), "apiId" character varying(50) NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "isFeatured" boolean NOT NULL DEFAULT false, "sortOrder" integer NOT NULL DEFAULT '0', "seasonStart" date, "seasonEnd" date, "currentSeason" integer, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_f4c22a253137e82ec78850e9b7f" UNIQUE ("slug"), CONSTRAINT "UQ_f7ed4419710e27e9b7820e4096b" UNIQUE ("apiId"), CONSTRAINT "PK_2275e1e3e32e9223298c3a0b514" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c3cb6ffa564432e025b182a435" ON "leagues" ("country") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f7ed4419710e27e9b7820e4096" ON "leagues" ("apiId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f4c22a253137e82ec78850e9b7" ON "leagues" ("slug") `);
        await queryRunner.query(`CREATE INDEX "IDX_d535cd077840bb3299757f3475" ON "leagues" ("sportId") `);
        await queryRunner.query(`CREATE TYPE "public"."match_events_type_enum" AS ENUM('GOAL', 'OWN_GOAL', 'PENALTY_GOAL', 'MISSED_PENALTY', 'YELLOW_CARD', 'RED_CARD', 'SUBSTITUTION', 'CORNER', 'FREE_KICK', 'OFFSIDE', 'FOUL', 'INJURY', 'VAR', 'KICKOFF', 'HALFTIME', 'FULLTIME', 'EXTRA_TIME', 'PENALTY_SHOOTOUT')`);
        await queryRunner.query(`CREATE TABLE "match_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "matchId" uuid NOT NULL, "teamId" uuid, "type" "public"."match_events_type_enum" NOT NULL, "minute" integer NOT NULL, "extraTime" integer, "playerName" character varying(100), "assistPlayerName" character varying(100), "playerId" uuid, "isHome" boolean NOT NULL DEFAULT false, "playerOut" character varying(100), "playerIn" character varying(100), "description" character varying(500), "detail" character varying(50), "coordinates" jsonb, "apiEventId" integer, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_34160ac79fb420bdc42a6b24854" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_59d2cbbbc49f74532e1a7e2eaa" ON "match_events" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_976dc51b390a33ce8c67d5cd7b" ON "match_events" ("minute") `);
        await queryRunner.query(`CREATE INDEX "IDX_c2da359d459a1dcfab2d195153" ON "match_events" ("teamId") `);
        await queryRunner.query(`CREATE INDEX "IDX_272a2f96fa5c7d89b8c362af05" ON "match_events" ("matchId") `);
        await queryRunner.query(`CREATE TYPE "public"."matches_status_enum" AS ENUM('SCHEDULED', 'LIVE', 'HALFTIME', 'FINISHED', 'POSTPONED', 'CANCELLED', 'ABANDONED', 'SUSPENDED')`);
        await queryRunner.query(`CREATE TYPE "public"."matches_result_enum" AS ENUM('HOME_WIN', 'AWAY_WIN', 'DRAW', 'PENDING')`);
        await queryRunner.query(`CREATE TABLE "matches" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "leagueId" uuid NOT NULL, "seasonId" uuid, "homeTeamId" uuid NOT NULL, "awayTeamId" uuid NOT NULL, "startTime" TIMESTAMP NOT NULL, "status" "public"."matches_status_enum" NOT NULL DEFAULT 'SCHEDULED', "result" "public"."matches_result_enum" NOT NULL DEFAULT 'PENDING', "homeScore" integer, "awayScore" integer, "homeHalfTimeScore" integer, "awayHalfTimeScore" integer, "homeExtraTimeScore" integer, "awayExtraTimeScore" integer, "homePenaltyScore" integer, "awayPenaltyScore" integer, "minute" integer, "period" character varying(20), "venue" character varying(255), "referee" character varying(100), "attendance" integer, "weather" character varying(50), "apiId" character varying(50) NOT NULL, "round" integer, "roundName" character varying(100), "isFeatured" boolean NOT NULL DEFAULT false, "finishedAt" TIMESTAMP, "odds" jsonb, "statistics" jsonb, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_c678ea60dd389dbfeaaf8c778c5" UNIQUE ("apiId"), CONSTRAINT "PK_8a22c7b2e0828988d51256117f4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cb1d5fb10c9a7398b475fd6961" ON "matches" ("startTime", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c678ea60dd389dbfeaaf8c778c" ON "matches" ("apiId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a182c2c9602fbab4e0cf680090" ON "matches" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_c8b2066966d4c910666964e0a9" ON "matches" ("startTime") `);
        await queryRunner.query(`CREATE INDEX "IDX_c5505de389fa5fca7ddce29fa4" ON "matches" ("awayTeamId") `);
        await queryRunner.query(`CREATE INDEX "IDX_999a74ecaebaf96816112445a0" ON "matches" ("homeTeamId") `);
        await queryRunner.query(`CREATE INDEX "IDX_107b8f72bdc17c14b57d5f469d" ON "matches" ("seasonId") `);
        await queryRunner.query(`CREATE INDEX "IDX_75354d5380a23b1b9c1427fbce" ON "matches" ("leagueId") `);
        await queryRunner.query(`CREATE TYPE "public"."prediction_batches_status_enum" AS ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "prediction_batches" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "name" character varying(200), "description" character varying(1000), "status" "public"."prediction_batches_status_enum" NOT NULL DEFAULT 'PENDING', "filters" jsonb NOT NULL, "predictionTypes" jsonb NOT NULL, "scenario" character varying(500), "totalMatches" integer NOT NULL DEFAULT '0', "processedMatches" integer NOT NULL DEFAULT '0', "totalPredictions" integer NOT NULL DEFAULT '0', "successfulPredictions" integer NOT NULL DEFAULT '0', "failedPredictions" integer NOT NULL DEFAULT '0', "averageConfidence" numeric(5,2), "startedAt" TIMESTAMP, "completedAt" TIMESTAMP, "estimatedCompletionAt" TIMESTAMP, "errorMessage" text, "progress" jsonb, "summary" jsonb, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e3340374efd4ba3938ad105d85f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7bc46be013a39010c5c8ca320c" ON "prediction_batches" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_60011f740cea98d5cb0973cd8c" ON "prediction_batches" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_268a13fe8fba2e853cdb6c4f11" ON "prediction_batches" ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."predictions_type_enum" AS ENUM('MATCH_WINNER', 'BOTH_TEAMS_SCORE', 'OVER_UNDER', 'HANDICAP', 'CORRECT_SCORE', 'FIRST_GOAL_SCORER', 'TOTAL_GOALS', 'HALF_TIME_RESULT', 'DOUBLE_CHANCE', 'DRAW_NO_BET', 'CLEAN_SHEET', 'WIN_TO_NIL', 'GOALS_ODD_EVEN', 'TEAM_TOTAL_GOALS', 'CORNERS', 'CARDS')`);
        await queryRunner.query(`CREATE TYPE "public"."predictions_outcome_enum" AS ENUM('HOME_WIN', 'AWAY_WIN', 'DRAW', 'OVER', 'UNDER', 'YES', 'NO', 'ODD', 'EVEN', 'CUSTOM')`);
        await queryRunner.query(`CREATE TYPE "public"."predictions_actualoutcome_enum" AS ENUM('HOME_WIN', 'AWAY_WIN', 'DRAW', 'OVER', 'UNDER', 'YES', 'NO', 'ODD', 'EVEN', 'CUSTOM')`);
        await queryRunner.query(`CREATE TYPE "public"."predictions_status_enum" AS ENUM('PENDING', 'CORRECT', 'INCORRECT', 'FINISHED', 'VOID', 'PUSH')`);
        await queryRunner.query(`CREATE TABLE "predictions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "matchId" uuid NOT NULL, "batchId" uuid, "type" "public"."predictions_type_enum" NOT NULL, "outcome" "public"."predictions_outcome_enum" NOT NULL, "actualOutcome" "public"."predictions_actualoutcome_enum", "status" "public"."predictions_status_enum" NOT NULL DEFAULT 'PENDING', "confidence" numeric(5,2) NOT NULL, "odds" numeric(8,5), "stake" numeric(5,2), "potentialWin" numeric(10,2), "actualWin" numeric(10,2), "reasoning" character varying(1000), "scenario" character varying(500), "details" jsonb, "contextData" jsonb, "resolvedAt" TIMESTAMP, "actualResult" jsonb, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "isCorrect" boolean, CONSTRAINT "PK_b92c9e4db595214b289f5e28adc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2c00b14b6320662bf17aee67fc" ON "predictions" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_8f57c46159d1baa78a293f4192" ON "predictions" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_dee818d9c88fef0ddd2c9fc9d5" ON "predictions" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_6a9655d032a58c32f5fd5a88e4" ON "predictions" ("batchId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3458aa50ebcc2f3df1d720161a" ON "predictions" ("matchId") `);
        await queryRunner.query(`CREATE INDEX "IDX_cd3302a5d7d146da1e001ace2b" ON "predictions" ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."chat_messages_role_enum" AS ENUM('USER', 'ASSISTANT', 'SYSTEM', 'TOOL')`);
        await queryRunner.query(`CREATE TABLE "chat_messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "conversationId" uuid NOT NULL, "role" "public"."chat_messages_role_enum" NOT NULL, "content" text NOT NULL, "tokens" integer, "cost" numeric(10,6), "responseTime" integer, "toolCalls" jsonb, "toolResults" jsonb, "entities" jsonb, "intent" jsonb, "context" jsonb, "isEdited" boolean NOT NULL DEFAULT false, "editedAt" TIMESTAMP, "originalContent" text, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_40c55ee0e571e268b0d3cd37d10" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a6f359922fb93e42d1b2daf38d" ON "chat_messages" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_47d59674564749030c4729d77c" ON "chat_messages" ("role") `);
        await queryRunner.query(`CREATE INDEX "IDX_45745953065384cc9c4264c2a3" ON "chat_messages" ("conversationId") `);
        await queryRunner.query(`CREATE TABLE "conversations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "title" character varying(200), "description" character varying(1000), "systemPrompt" text, "isActive" boolean NOT NULL DEFAULT true, "isPinned" boolean NOT NULL DEFAULT false, "messageCount" integer NOT NULL DEFAULT '0', "tokensUsed" integer NOT NULL DEFAULT '0', "estimatedCost" numeric(10,6) NOT NULL DEFAULT '0', "lastMessageAt" TIMESTAMP, "tags" jsonb, "metadata" jsonb, "summary" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ee34f4f7ced4ec8681f26bf04ef" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ae0652398784e0276bf69e5bdd" ON "conversations" ("updatedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_98e7c5d5a223e5c7451459e7dc" ON "conversations" ("isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_a9b3b5d51da1c75242055338b5" ON "conversations" ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."payments_status_enum" AS ENUM('PENDING', 'SUCCESS', 'FAILED', 'CANCELLED', 'REFUNDED', 'PARTIALLY_REFUNDED')`);
        await queryRunner.query(`CREATE TYPE "public"."payments_type_enum" AS ENUM('SUBSCRIPTION', 'ONE_TIME', 'RENEWAL', 'UPGRADE', 'DOWNGRADE')`);
        await queryRunner.query(`CREATE TYPE "public"."payments_method_enum" AS ENUM('CARD', 'BANK_TRANSFER', 'USSD', 'QR', 'MOBILE_MONEY')`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "subscriptionId" uuid, "paystackReference" character varying(255) NOT NULL, "status" "public"."payments_status_enum" NOT NULL DEFAULT 'PENDING', "type" "public"."payments_type_enum" NOT NULL DEFAULT 'SUBSCRIPTION', "method" "public"."payments_method_enum", "amount" numeric(10,2) NOT NULL, "fees" numeric(10,2), "netAmount" numeric(10,2), "currency" character varying(10) NOT NULL DEFAULT 'NGN', "description" character varying(255), "ipAddress" inet, "userAgent" character varying(255), "paidAt" TIMESTAMP, "failedAt" TIMESTAMP, "refundedAt" TIMESTAMP, "refundedAmount" numeric(10,2), "failureReason" character varying(500), "paystackData" jsonb, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_e2c642756a34c2ec569f1b44631" UNIQUE ("paystackReference"), CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8277a466232344577740a61344" ON "payments" ("createdAt") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e2c642756a34c2ec569f1b4463" ON "payments" ("paystackReference") `);
        await queryRunner.query(`CREATE INDEX "IDX_32b41cdb985a296213e9a928b5" ON "payments" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_2017d0cbfdbfec6b1b388e6aa0" ON "payments" ("subscriptionId") `);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_plan_enum" AS ENUM('FREE', 'PRO', 'ULTRA')`);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_status_enum" AS ENUM('ACTIVE', 'CANCELLED', 'EXPIRED', 'SUSPENDED', 'PENDING', 'TRIALING')`);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_billingcycle_enum" AS ENUM('MONTHLY', 'QUARTERLY', 'YEARLY')`);
        await queryRunner.query(`CREATE TABLE "subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "plan" "public"."subscriptions_plan_enum" NOT NULL, "status" "public"."subscriptions_status_enum" NOT NULL DEFAULT 'PENDING', "billingCycle" "public"."subscriptions_billingcycle_enum" NOT NULL DEFAULT 'MONTHLY', "amount" numeric(10,2) NOT NULL, "currency" character varying(10) NOT NULL DEFAULT 'NGN', "startDate" TIMESTAMP NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "trialEndsAt" TIMESTAMP, "cancelledAt" TIMESTAMP, "nextBillingAt" TIMESTAMP, "currentPeriodStart" TIMESTAMP, "currentPeriodEnd" TIMESTAMP, "paystackSubscriptionId" character varying(255), "paystackCustomerId" character varying(255), "paystackPlanId" character varying(255), "autoRenew" boolean NOT NULL DEFAULT true, "failedPaymentAttempts" integer NOT NULL DEFAULT '0', "lastPaymentAt" TIMESTAMP, "lastFailedPaymentAt" TIMESTAMP, "cancellationReason" character varying(500), "features" jsonb, "usage" jsonb, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_fbdba4e2ac694cf8c9cecf4dc84" UNIQUE ("userId"), CONSTRAINT "REL_fbdba4e2ac694cf8c9cecf4dc8" UNIQUE ("userId"), CONSTRAINT "PK_a87248d73155605cf782be9ee5e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_523af772747ee6f53767e88e93" ON "subscriptions" ("paystackSubscriptionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_952eabdfeff473584fb7491f98" ON "subscriptions" ("expiresAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_95d52cafe172d597df468e507a" ON "subscriptions" ("plan") `);
        await queryRunner.query(`CREATE INDEX "IDX_6ccf973355b70645eff37774de" ON "subscriptions" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_fbdba4e2ac694cf8c9cecf4dc8" ON "subscriptions" ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('USER', 'MODERATOR', 'ADMIN')`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED', 'BANNED')`);
        await queryRunner.query(`CREATE TYPE "public"."users_subscriptionplan_enum" AS ENUM('FREE', 'PRO', 'ULTRA')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying(255) NOT NULL, "username" character varying(100) NOT NULL, "password" character varying(255) NOT NULL, "firstName" character varying(100), "lastName" character varying(100), "avatar" character varying(255), "phoneNumber" character varying(20), "dateOfBirth" date, "country" character varying(100), "timezone" character varying(10), "preferredLanguage" character varying(10), "role" "public"."users_role_enum" NOT NULL DEFAULT 'USER', "status" "public"."users_status_enum" NOT NULL DEFAULT 'ACTIVE', "subscriptionPlan" "public"."users_subscriptionplan_enum" NOT NULL DEFAULT 'FREE', "subscriptionExpiresAt" TIMESTAMP, "emailVerified" boolean NOT NULL DEFAULT false, "emailVerifiedAt" TIMESTAMP, "phoneVerified" boolean NOT NULL DEFAULT false, "isActive" boolean NOT NULL DEFAULT true, "lastLoginAt" TIMESTAMP, "lastLoginIp" inet, "preferences" jsonb, "metadata" jsonb, "monthlyPredictions" integer NOT NULL DEFAULT '0', "monthlyChatMessages" integer NOT NULL DEFAULT '0', "usagePeriodStart" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_fe0bb3f6520ee0469504521e71" ON "users" ("username") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "FK_57de40bc620f456c7311aa3a1e6" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "FK_fd11aa87698d5a784713b9de978" FOREIGN KEY ("deviceId") REFERENCES "devices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "devices" ADD CONSTRAINT "FK_e8a5d59f0ac3040395f159507c6" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_610102b60fea1455310ccd299de" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "seasons" ADD CONSTRAINT "FK_a7cb1734e4ef424bf9422b1c0df" FOREIGN KEY ("leagueId") REFERENCES "leagues"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teams" ADD CONSTRAINT "FK_a2e8bdf2708d44fab55ee1ff751" FOREIGN KEY ("leagueId") REFERENCES "leagues"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leagues" ADD CONSTRAINT "FK_d535cd077840bb3299757f34755" FOREIGN KEY ("sportId") REFERENCES "sports"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "match_events" ADD CONSTRAINT "FK_272a2f96fa5c7d89b8c362af058" FOREIGN KEY ("matchId") REFERENCES "matches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "match_events" ADD CONSTRAINT "FK_c2da359d459a1dcfab2d1951532" FOREIGN KEY ("teamId") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matches" ADD CONSTRAINT "FK_75354d5380a23b1b9c1427fbce1" FOREIGN KEY ("leagueId") REFERENCES "leagues"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matches" ADD CONSTRAINT "FK_107b8f72bdc17c14b57d5f469d1" FOREIGN KEY ("seasonId") REFERENCES "seasons"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matches" ADD CONSTRAINT "FK_999a74ecaebaf96816112445a09" FOREIGN KEY ("homeTeamId") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matches" ADD CONSTRAINT "FK_c5505de389fa5fca7ddce29fa49" FOREIGN KEY ("awayTeamId") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prediction_batches" ADD CONSTRAINT "FK_268a13fe8fba2e853cdb6c4f11c" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "predictions" ADD CONSTRAINT "FK_cd3302a5d7d146da1e001ace2bd" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "predictions" ADD CONSTRAINT "FK_3458aa50ebcc2f3df1d720161a3" FOREIGN KEY ("matchId") REFERENCES "matches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "predictions" ADD CONSTRAINT "FK_6a9655d032a58c32f5fd5a88e4d" FOREIGN KEY ("batchId") REFERENCES "prediction_batches"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_messages" ADD CONSTRAINT "FK_45745953065384cc9c4264c2a3d" FOREIGN KEY ("conversationId") REFERENCES "conversations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversations" ADD CONSTRAINT "FK_a9b3b5d51da1c75242055338b59" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_2017d0cbfdbfec6b1b388e6aa08" FOREIGN KEY ("subscriptionId") REFERENCES "subscriptions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_fbdba4e2ac694cf8c9cecf4dc84" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_fbdba4e2ac694cf8c9cecf4dc84"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_2017d0cbfdbfec6b1b388e6aa08"`);
        await queryRunner.query(`ALTER TABLE "conversations" DROP CONSTRAINT "FK_a9b3b5d51da1c75242055338b59"`);
        await queryRunner.query(`ALTER TABLE "chat_messages" DROP CONSTRAINT "FK_45745953065384cc9c4264c2a3d"`);
        await queryRunner.query(`ALTER TABLE "predictions" DROP CONSTRAINT "FK_6a9655d032a58c32f5fd5a88e4d"`);
        await queryRunner.query(`ALTER TABLE "predictions" DROP CONSTRAINT "FK_3458aa50ebcc2f3df1d720161a3"`);
        await queryRunner.query(`ALTER TABLE "predictions" DROP CONSTRAINT "FK_cd3302a5d7d146da1e001ace2bd"`);
        await queryRunner.query(`ALTER TABLE "prediction_batches" DROP CONSTRAINT "FK_268a13fe8fba2e853cdb6c4f11c"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP CONSTRAINT "FK_c5505de389fa5fca7ddce29fa49"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP CONSTRAINT "FK_999a74ecaebaf96816112445a09"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP CONSTRAINT "FK_107b8f72bdc17c14b57d5f469d1"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP CONSTRAINT "FK_75354d5380a23b1b9c1427fbce1"`);
        await queryRunner.query(`ALTER TABLE "match_events" DROP CONSTRAINT "FK_c2da359d459a1dcfab2d1951532"`);
        await queryRunner.query(`ALTER TABLE "match_events" DROP CONSTRAINT "FK_272a2f96fa5c7d89b8c362af058"`);
        await queryRunner.query(`ALTER TABLE "leagues" DROP CONSTRAINT "FK_d535cd077840bb3299757f34755"`);
        await queryRunner.query(`ALTER TABLE "teams" DROP CONSTRAINT "FK_a2e8bdf2708d44fab55ee1ff751"`);
        await queryRunner.query(`ALTER TABLE "seasons" DROP CONSTRAINT "FK_a7cb1734e4ef424bf9422b1c0df"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_610102b60fea1455310ccd299de"`);
        await queryRunner.query(`ALTER TABLE "devices" DROP CONSTRAINT "FK_e8a5d59f0ac3040395f159507c6"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "FK_fd11aa87698d5a784713b9de978"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "FK_57de40bc620f456c7311aa3a1e6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fe0bb3f6520ee0469504521e71"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_subscriptionplan_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fbdba4e2ac694cf8c9cecf4dc8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6ccf973355b70645eff37774de"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_95d52cafe172d597df468e507a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_952eabdfeff473584fb7491f98"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_523af772747ee6f53767e88e93"`);
        await queryRunner.query(`DROP TABLE "subscriptions"`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_billingcycle_enum"`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_plan_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2017d0cbfdbfec6b1b388e6aa0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_32b41cdb985a296213e9a928b5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e2c642756a34c2ec569f1b4463"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8277a466232344577740a61344"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payments_method_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payments_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payments_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a9b3b5d51da1c75242055338b5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_98e7c5d5a223e5c7451459e7dc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ae0652398784e0276bf69e5bdd"`);
        await queryRunner.query(`DROP TABLE "conversations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_45745953065384cc9c4264c2a3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_47d59674564749030c4729d77c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a6f359922fb93e42d1b2daf38d"`);
        await queryRunner.query(`DROP TABLE "chat_messages"`);
        await queryRunner.query(`DROP TYPE "public"."chat_messages_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cd3302a5d7d146da1e001ace2b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3458aa50ebcc2f3df1d720161a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6a9655d032a58c32f5fd5a88e4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dee818d9c88fef0ddd2c9fc9d5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8f57c46159d1baa78a293f4192"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2c00b14b6320662bf17aee67fc"`);
        await queryRunner.query(`DROP TABLE "predictions"`);
        await queryRunner.query(`DROP TYPE "public"."predictions_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."predictions_actualoutcome_enum"`);
        await queryRunner.query(`DROP TYPE "public"."predictions_outcome_enum"`);
        await queryRunner.query(`DROP TYPE "public"."predictions_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_268a13fe8fba2e853cdb6c4f11"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_60011f740cea98d5cb0973cd8c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7bc46be013a39010c5c8ca320c"`);
        await queryRunner.query(`DROP TABLE "prediction_batches"`);
        await queryRunner.query(`DROP TYPE "public"."prediction_batches_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_75354d5380a23b1b9c1427fbce"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_107b8f72bdc17c14b57d5f469d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_999a74ecaebaf96816112445a0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c5505de389fa5fca7ddce29fa4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c8b2066966d4c910666964e0a9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a182c2c9602fbab4e0cf680090"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c678ea60dd389dbfeaaf8c778c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cb1d5fb10c9a7398b475fd6961"`);
        await queryRunner.query(`DROP TABLE "matches"`);
        await queryRunner.query(`DROP TYPE "public"."matches_result_enum"`);
        await queryRunner.query(`DROP TYPE "public"."matches_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_272a2f96fa5c7d89b8c362af05"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c2da359d459a1dcfab2d195153"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_976dc51b390a33ce8c67d5cd7b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_59d2cbbbc49f74532e1a7e2eaa"`);
        await queryRunner.query(`DROP TABLE "match_events"`);
        await queryRunner.query(`DROP TYPE "public"."match_events_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d535cd077840bb3299757f3475"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f4c22a253137e82ec78850e9b7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f7ed4419710e27e9b7820e4096"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c3cb6ffa564432e025b182a435"`);
        await queryRunner.query(`DROP TABLE "leagues"`);
        await queryRunner.query(`DROP TYPE "public"."leagues_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a2e8bdf2708d44fab55ee1ff75"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_de8536da4945fe980f4a61900d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1000526725818dc4f1fa10c05c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_960b513ff2e8bc3228b7d90884"`);
        await queryRunner.query(`DROP TABLE "teams"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a7cb1734e4ef424bf9422b1c0d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e20814074bbf37638cb4affa08"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b6c0d664ab8e5ad1c0df11641f"`);
        await queryRunner.query(`DROP TABLE "seasons"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_be96c1d313b6d198a17b08f4c6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7469a21a84308f52d4b9d14cdd"`);
        await queryRunner.query(`DROP TABLE "sports"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_610102b60fea1455310ccd299d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4542dd2f38a61354a040ba9fd5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_56b91d98f71e3d1b649ed6e9f3"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`DROP TYPE "public"."refresh_tokens_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e8a5d59f0ac3040395f159507c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_854ce23dfa9a30aa4ddfc6f78f"`);
        await queryRunner.query(`DROP TABLE "devices"`);
        await queryRunner.query(`DROP TYPE "public"."devices_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."devices_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_57de40bc620f456c7311aa3a1e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fd11aa87698d5a784713b9de97"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e9f62f5dcb8a54b84234c9e7a0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_50762206f116cd47d1c3fec396"`);
        await queryRunner.query(`DROP TABLE "sessions"`);
        await queryRunner.query(`DROP TYPE "public"."sessions_status_enum"`);
    }

}
